apiVersion: v1
kind: Pod
metadata:
  name: pod-with-storage
spec:
  containers:
  - name: volume-container
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
      - mountPath: "/data"
        name: storage-volume
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: mypvc

